### ISSUE TITLE
Brendan L Homework

### ISSUE THREAD

**Issue by lewis2ba** [ga-dc/thanksgiving-homework#32]
Part 1
https://github.com/lewis2ba/movie-browser
Comfort - 3/5
Completeness 5/5
This helped me get some of the concepts but I still think I have a long way to go. Definitely needs a refactor.

Part 2
No idea what is going on here. I'm lost
How is Express related to the MEAN stack?
Express is the E in the MEAN stack. It is a web application framework that helps organize your app into an MVC
How does Express differ from a framework like Sinatra?
Javascript vs Ruby. 
How would you choose one over the other when starting a new project?
If you prefer JS use Express, if you prefer Ruby use Sinatra
What big picture questions do you have?
I need more clarification on the 2nd and 3rd question.

**Comment by RobertAKARobin** [comment]
Nice movie browser!

Express is just like Sinatra in that it's a wrapper on top of another server. The server you use with Sinatra is WEBrick. By itself, WEBrick is pretty tough to use, so we use Sinatra on top of it. Express is to Node the same way.

As for the differences between Sinatra and Express, you got it: it's pretty much just Javascript vs Ruby. Personally, I'd use Sinatra/Rails for anything involving databases because ActiveRecord is way nicer than Mongo or Sequelize in JS. But I'll use Express for just about everything else because Javascript's a more universal language.
