### ISSUE TITLE
Alea - Thanksgiving HW 1&2

### ISSUE THREAD

**Issue by ghost** [ga-dc/thanksgiving-homework#4]
Part 1
https://github.com/ScreenName4eva/infinite-giphy

I spent a lot of time trying to do this how we learned it in class and it didn't work out for me.  When I went and looked at all the solutions for all the options (not just giphy) I noticed none of them were done in the way we practiced in class so it took more time to research how to do things the way the solution showed.  I went back to the curriculum page to compare it to my notes and noticed that half or less than half of the examples were using ruby which made things a little more confusing but I got through it. 

In the end when I broke down the solution I understand what each part is doing, however I really don't understand how to achieve the same thing using what we learned in class instead of the newly introduced way in the solution.  Maybe a mini lesson could be done to either break down the new way to do this as shown in the solution or show how to achieve the same thing with how we did it in class and not using getjson.  

Part 2 
How is Express related to the MEAN stack?
Express puts the E in MEAN. It's just one of the frameworks to build web apps in node.

How does Express differ from a framework like Sinatra?
Express uses javascript and sinatra uses ruby 

How would you choose one over the other when starting a new project?
I guess it depends on what i'm building and what backend language i'm using 

What big picture questions do you have?

When does it make sense to use each of the different parts of MEAN?
Why didn't we use express with the homework?

**Comment by mattscilipoti** [comment]
I'm not sure what you mean when you say it's not "done in the way we practiced in class".  We covered the 2 ways to utilize ajax calls: with a callback or with a promise.  The inifiniteGiphy solution utilizes a callback.  This solution for Spotify uses a promise: https://github.com/ga-dc/spotify-me/tree/solution_oop_adam.

 If you are asking about the use of `getJson` instead of `ajax`, getJson is an ajax call, preconfigured for a get request with a json response.  From http://api.jquery.com/jquery.getjson/: 

> This is a shorthand Ajax function, which is equivalent to:

``` js
$.ajax({
  dataType: "json",
  url: url,
  data: data,
  success: success
});
```

Does that help?

This blog post from another GA student may help: https://medium.com/@KDweber89/ajax-vs-getjson-ca910fa6854e#.wfjfa3f18

**Comment by ghost** [comment]
I think the issue was that all the solutions had getJSON when we just learned the ajax format, which made it confusing when I was trying to check my work.  After we learned getJSON it made sense but not before, especially after learning a bunch of different stuff at once.
