### ISSUE TITLE
Eric Stennett - Part 2 - Homework

### ISSUE THREAD

**Issue by estennett** [ga-dc/thanksgiving-homework#51]
```
How is Express related to the MEAN stack?
```

From my understanding Express is the 'E' in the MEAN stack.  It provides the server-side framework for a MEAN stack app.

```
How does Express differ from a framework like Sinatra?
```

Express is written in JavaScript, while Sinatra is written in Ruby.  Express gives you more flexibility in coding, where Sinatra was more structured, however not as structured as Rails.

```
How would you choose one over the other when starting a new project?
```

I think it depends on the scope of your project.  It seems that Express would lend itself well to single page web apps, whereas Sinatra might be better for multi-page web apps.  If you need to have a high level of customization, Express would be the superior option it seems.

```
What big picture questions do you have?
```

I would like to understand what other backend frame works are out there and how they relate to Rails, Sinatra, and Express.

**Comment by nolds9** [comment]
:+1: Really liked your high level answers to these questions. We will get a much better picture of the how the pieces in the MEAN stack fit together in the next few weeks, but is still worthwhile to study the parts in isolation to compare them to other alternatives because there are different tech stacks out there!
