### ISSUE TITLE
Pt 2

### ISSUE THREAD

**Issue by Briik** [ga-dc/thanksgiving-homework#53]
Got completely lost on Good Old Form (step 4) of Expressworks. Currently thinking that the instructions are actually asking me to make a view with an html form in it, instead of it being supplied as in previous steps, will have to look at that again.

How is Express related to the MEAN stack?
Express is mean, ergo it does its job perfectly... Express lets the user create their own MVC framework, views/templates, etc.
How does Express differ from a framework like Sinatra?
It's not named after a dead white guy. Probably drinks fair-trade coffee and justifies spending its parents' money on trendy whiskey by saying they neglected it during development.
How would you choose one over the other when starting a new project?
If I wanted to show how awesome I am at JavaScript, I'd choose Express.  If I was writing a thesis on the utility of obscure punctuation marks, I'd encourage others to use Express.
What big picture questions do you have?
Why? Other than being a way for JavaScript developers to not have to learn another language, why is a MEAN stack better than other options?

**Comment by RobertAKARobin** [comment]
More specifically, Express is the 'E' in 'MEAN' (the others being Mongo, Angular, and Node).

:+1: for creativity. Sinatra is to WEBrick (the underlying server) as Express is to Node.

Language preference is pretty much the number one reason. There are more nuanced reasons: the MEAN stack is faster than the Rails stack because it manages memory more efficiently.
