### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by pzhang87** [ga-dc/thanksgiving-homework#62]
Part 1: https://github.com/pzhang87/infinite-giphy
Comfort: 4
Completeness: 4

Wasn't so bad once I remembered how to do stuff with the window!

Part 2:
1. How is Express related to the MEAN stack?
Express is the E in the MEAN stack, and lets us use server-side Javascript.  It's built off of node.js

How does Express differ from a framework like Sinatra?
I think the large difference here is how it handles stuff asynchronously, which makes it faster but more demanding in terms of writing good code?  I'm also under the impression that Sinatra is slightly more opinionated than Express.

How would you choose one over the other when starting a new project?
From what I've read, Express is very good at handling single page apps that scale well, while Sinatra (and Rails) are better at handling stuff with larger databases (?)

What big picture questions do you have?
Not sure how MongoDB relates here, since it's NoSQL?

**Comment by nolds9** [comment]
:+1: Good job tackling this assignment, really like your solution! We will get a much better picture of the how the pieces in the MEAN stack fit together in the next few weeks, but is still worthwhile to study the parts in isolation to compare them to other alternatives because there are different tech stacks out there!
